/**
 * Source Attribution Types
 * 
 * Defines alert source types for visual attribution badges.
 * This is a UI-only enhancement - no database changes required.
 */

export type AlertSource =
    | 'simulation'      // Generated by simulation engine
    | 'log_ingestion'   // From uploaded log files
    | 'correlated'      // Generated by correlation engine
    | 'automated'       // Triggered by automation rules
    | 'manual'          // Manually created
    | 'unknown';        // Could not determine source

export interface SourceBadgeConfig {
    label: string;
    color: string;
    bgColor: string;
    icon: string;
    description: string;
}

export const SOURCE_CONFIGS: Record<AlertSource, SourceBadgeConfig> = {
    simulation: {
        label: 'Simulation',
        color: 'text-blue-700',
        bgColor: 'bg-blue-100',
        icon: '🔵',
        description: 'Generated by threat simulation engine'
    },
    log_ingestion: {
        label: 'Log Analysis',
        color: 'text-green-700',
        bgColor: 'bg-green-100',
        icon: '🟢',
        description: 'Detected from uploaded log files'
    },
    correlated: {
        label: 'Correlated',
        color: 'text-yellow-700',
        bgColor: 'bg-yellow-100',
        icon: '🟡',
        description: 'Linked to related security events'
    },
    automated: {
        label: 'Automated',
        color: 'text-purple-700',
        bgColor: 'bg-purple-100',
        icon: '🟣',
        description: 'Auto-generated by automation rules'
    },
    manual: {
        label: 'Manual',
        color: 'text-gray-700',
        bgColor: 'bg-gray-100',
        icon: '⚪',
        description: 'Manually created by analyst'
    },
    unknown: {
        label: 'Unknown',
        color: 'text-gray-500',
        bgColor: 'bg-gray-50',
        icon: '⚫',
        description: 'Source not identified'
    }
};
